# Constants
I2C_SCL_PIN = 22
I2C_SDA_PIN = 21
I2C_FREQ = 115200

NH3_THRESHOLD = 2.88
CO2_THRESHOLD = 1000

# Flags to enable/disable components
ENABLE_I2C = True
ENABLE_BUZZER = True
ENABLE_BME280 = True
ENABLE_SCD4X = True
ENABLE_MQ135 = True
ENABLE_FLAME_SENSOR = True
ENABLE_DS1302 = True
ENABLE_INA219 = False
ENABLE_LSM303D = True
ENABLE_L3GD20 = False
ENABLE_UART_COMM = True

ENABLE_INFO_PRINT = True
ENABLE_ERROR_PRINT = True
